### ISSUE TITLE
bungee error on startup!

### ISSUE THREAD

**Issue by general2811** [Fabricio20/HubBasics#108]
`[11:06:48 ERROR]: java.io.IOException: Das System kann den angegebenen Pfad nicht finden
[11:06:48 ERROR]:       at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[11:06:48 ERROR]:       at java.io.File.createNewFile(Unknown Source)
[11:06:48 ERROR]:       at net.notfab.hubbasics.bungee.managers.ConfigHandler.writeToFile(ConfigHandler.java:41)
[11:06:48 ERROR]:       at net.notfab.hubbasics.bungee.managers.ConfigHandler.<init>(ConfigHandler.java:13)
[11:06:48 ERROR]:       at net.notfab.hubbasics.bungee.HubBasics.onEnable(HubBasics.java:24)
[11:06:48 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
[11:06:48 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
[11:06:48 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[11:06:48 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[11:06:48 ERROR]: java.io.IOException: Das System kann den angegebenen Pfad nicht finden
[11:06:48 ERROR]:       at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[11:06:48 ERROR]:       at java.io.File.createNewFile(Unknown Source)
[11:06:48 ERROR]:       at net.notfab.hubbasics.bungee.managers.ConfigHandler.writeToFile(ConfigHandler.java:41)
[11:06:48 ERROR]:       at net.notfab.hubbasics.bungee.managers.ConfigHandler.<init>(ConfigHandler.java:18)
[11:06:48 ERROR]:       at net.notfab.hubbasics.bungee.HubBasics.onEnable(HubBasics.java:24)
[11:06:48 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
[11:06:48 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
[11:06:48 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[11:06:48 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

**Comment by Fabricio20** [comment]
Hey, looks like you are missing a config file, get it from here: https://github.com/Fabricio20/HubBasics/tree/master/HB-Bungee/src/main/resources

I'll check why it's not setting it up.

**Comment by Fabricio20** [comment]
Should be fixed as of today.
