### ISSUE TITLE
Crash on plugin load

### ISSUE THREAD

**Issue by SidiXis** [Fabricio20/HubBasics#12]
I'm getting crashes all the time:

[02:36:42 ERROR]: Error occurred while enabling HubBasics v3.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at me.Fabricio20.Main.registerCommands(Main.java:134) ~[?:?]
        at me.Fabricio20.Main.initPlugin(Main.java:111) ~[?:?]
        at me.Fabricio20.Main.onEnable(Main.java:87) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:742) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:629) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:627) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:530) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_31]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_31]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
        ... 19 more

What to do?

**Comment by Fabricio20** [comment]
Error related to server version, please send me your full version string so I can send you the instructions.

**Comment by SidiXis** [comment]
Didn't quite understand what you meant - I'll send everything from reload to that error.

[02:01:59 INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
[02:01:59 INFO]: [HealthBar] Loading HealthBar v1.8.2
[02:01:59 INFO]: [LampControl] Loading LampControl v2.5.3
[02:01:59 INFO]: [OpenInv] Loading OpenInv v2.2.8
[02:01:59 INFO]: [Essentials] Loading Essentials vTeamCity
[02:01:59 INFO]: [WorldBorder] Loading WorldBorder v1.8.1
[02:01:59 INFO]: [AntiLog] Loading AntiLog v1.6.1
[02:01:59 INFO]: [PvPControl] Loading PvPControl v1.5
[02:01:59 INFO]: [ProtocolLib] Loading ProtocolLib v3.6.3-SNAPSHOT
[02:01:59 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b691
[02:01:59 INFO]: [WorldGuard] Loading WorldGuard v6.0.0-beta-05.1569-
[02:01:59 INFO]: [VipSms] Loading VipSms v1.08
[02:01:59 INFO]: [AutoSaveWorld] Loading AutoSaveWorld v4.14.1
[02:01:59 INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v2.1.5
[02:01:59 INFO]: [ArmorStandGUI] Loading ArmorStandGUI v1.0.1
[02:01:59 INFO]: [EssentialsChat] Loading EssentialsChat vTeamCity
[02:01:59 INFO]: [PermissionsEx] Loading PermissionsEx v1.23.1
[02:01:59 WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
[02:01:59 INFO]: [RandomTeleport] Loading RandomTeleport vmaven-version-number
[02:01:59 INFO]: [MineResetLite] Loading MineResetLite v0.3.6
[02:01:59 INFO]: [Vault] Loading Vault v1.5.2-b33
[02:01:59 INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[02:01:59 INFO]: [ChestMaster] Loading ChestMaster v1.5
[02:01:59 INFO]: [HubBasics] Loading HubBasics v3.0.5
[02:01:59 INFO]: [Paintball] Loading Paintball v1.3.3
[02:01:59 INFO]: [ServerlistMOTD] Loading ServerlistMOTD v4.2
[02:01:59 INFO]: [PlotSquared] Loading PlotSquared v2.7.4
[02:01:59 INFO]: [HolographicDisplays] Loading HolographicDisplays v2.1.4
[02:01:59 INFO]: [PlayerPoints] Loading PlayerPoints v2.1.3
[02:01:59 INFO]: [ChestCommands] Loading ChestCommands v3.1
[02:01:59 INFO]: [BungeeTabListPlus_BukkitBridge] Loading BungeeTabListPlus_BukkitBridge v7
[02:01:59 INFO]: [TouchscreenHolograms] Loading TouchscreenHolograms v1.3
[02:01:59 INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v2.1.3
[02:01:59 INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
[02:01:59 INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[02:01:59 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.EditSession injected.
[02:01:59 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.Operations injected.
[02:01:59 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.SchematicCommands injected.
[02:01:59 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.ScriptingCommands injected.
[02:01:59 INFO]: [AsyncWorldEditInjector] Enabled
[02:01:59 INFO]: [ProtocolLib] Enabling ProtocolLib v3.6.3-SNAPSHOT
[02:01:59 INFO]: [ProtocolLib] Started structure compiler thread.
[02:01:59 INFO]: [AutoSaveWorld] Enabling AutoSaveWorld v4.14.1
[02:01:59 INFO]: [Vault] Enabling Vault v1.5.2-b33
[02:01:59 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[02:02:00 INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[02:02:00 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[02:02:00 INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[02:02:00 INFO]: [Vault] Enabled Version 1.5.2-b33
[02:02:00 INFO]: [PlotSquared] Enabling PlotSquared v2.7.4
[02:02:00 INFO]: [Plot]  - Adding flag: greeting
[02:02:00 INFO]: [Plot]  - Adding flag: farewell
[02:02:00 INFO]: [Plot]  - Adding flag: feed
[02:02:00 INFO]: [Plot]  - Adding flag: heal
[02:02:00 INFO]: [Plot]  - Adding flag: notify-enter
[02:02:00 INFO]: [Plot]  - Adding flag: notify-leave
[02:02:00 INFO]: [Plot]  - Adding flag: item-drop
[02:02:00 INFO]: [Plot]  - Adding flag: invincible
[02:02:00 INFO]: [Plot]  - Adding flag: instabreak
[02:02:00 INFO]: [Plot]  - Adding flag: drop-protection
[02:02:00 INFO]: [Plot]  - Adding flag: forcefield
[02:02:00 INFO]: [Plot]  - Adding flag: titles
[02:02:00 INFO]: [Plot]  - Adding flag: pve
[02:02:00 INFO]: [Plot]  - Adding flag: pvp
[02:02:00 INFO]: [Plot]  - Adding flag: no-worldedit
[02:02:00 INFO]: [Plot]  - Adding flag: fly
[02:02:00 INFO]: [Plot]  - Adding flag: explosion
[02:02:00 INFO]: [Plot]  - Adding flag: hostile-interact
[02:02:00 INFO]: [Plot]  - Adding flag: hostile-attack
[02:02:00 INFO]: [Plot]  - Adding flag: animal-interact
[02:02:00 INFO]: [Plot]  - Adding flag: animal-attack
[02:02:00 INFO]: [Plot]  - Adding flag: tamed-interact
[02:02:00 INFO]: [Plot]  - Adding flag: tamed-attack
[02:02:00 INFO]: [Plot]  - Adding flag: misc-interact
[02:02:00 INFO]: [Plot]  - Adding flag: hanging-place
[02:02:00 INFO]: [Plot]  - Adding flag: hanging-break
[02:02:00 INFO]: [Plot]  - Adding flag: vehicle-use
[02:02:00 INFO]: [Plot]  - Adding flag: vehicle-place
[02:02:00 INFO]: [Plot]  - Adding flag: vehicle-break
[02:02:00 INFO]: [Plot]  - Adding flag: place
[02:02:00 INFO]: [Plot]  - Adding flag: break
[02:02:00 INFO]: [Plot]  - Adding flag: use
[02:02:00 INFO]: [Plot]  - Adding flag: gamemode
[02:02:00 INFO]: [Plot]  - Adding flag: price
[02:02:00 INFO]: [Plot]  - Adding flag: time
[02:02:00 INFO]: [Plot]  - Adding flag: weather
[02:02:00 INFO]: [Plot] Metrics enabled.
[02:02:00 INFO]: PlotSquared is now enabled
[02:02:00 WARN]: [AutoSaveWorld] Plugin PlotSquared attempted to establish connection socket://localhost:3306 in main server thread
[02:02:00 INFO]: [WARNING] Found 5 plots in DB for non existant world; 'fb'.
[02:02:00 INFO]: [WARNING] - Please create the world/s or remove the plots using the purge command
[02:02:00 INFO]: [Plot]  PlotSquared is using Offline Mode UUIDs either because of user preference, or because you are using an old version of Bukkit
[02:02:00 INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[02:02:00 INFO]: WEPIF: Using the Bukkit Permissions API.
[02:02:00 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[02:02:00 INFO]: [HealthBar] Enabling HealthBar v1.8.2
[02:02:00 INFO]: [LampControl] Enabling LampControl v2.5.3
[02:02:00 INFO]: [LampControl] Lamp Control v2.5.3 is the latest version available, and the updatability of it is: NO_UPDATE. The latest version is for 1.8.1 only.
[02:02:00 INFO]: [LampControl] LampControl v2.5.3 is enabled!
[02:02:00 INFO]: [OpenInv] Enabling OpenInv v2.2.8
[02:02:00 INFO]: [Essentials] Enabling Essentials vTeamCity
[02:02:00 INFO]: Bukkit version format changed. Version not checked.
[02:02:00 INFO]: git-Spigot-da32fe1-37102a0 (MC: 1.8)
[02:02:00 INFO]: 1.8-R0.1-SNAPSHOT
[02:02:00 INFO]: Using locale pl
[02:02:01 INFO]: Using locale pl
[02:02:01 INFO]: [Vault][Economy] Essentials Economy hooked.
[02:02:01 INFO]: Essentials: Using config file enhanced permissions.
[02:02:01 INFO]: Permissions listed in as player-commands will be given to all users.
[02:02:01 INFO]: [WorldBorder] Enabling WorldBorder v1.8.1
[02:02:01 INFO]: [WorldBorder] [CONFIG] Using elliptic/round border, knockback of 3.0 blocks, and timer delay of 5.
[02:02:01 INFO]: [WorldBorder] [CONFIG] Border-checking timed task started.
[02:02:01 INFO]: [WorldBorder] [CONFIG] World "world" has border radius 3000 at X: 260.9 Z: 240.6
[02:02:01 INFO]: [WorldBorder] For reference, the main world's spawn location is at X: 260.0 Y: 64.0 Z: 240.0
[02:02:01 INFO]: [AntiLog] Enabling AntiLog v1.6.1
[02:02:01 INFO]: [AntiLog] Settings loaded successfully!
[02:02:01 INFO]: [PvPControl] Enabling PvPControl v1.5
[02:02:01 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b691
[02:02:01 INFO]: [Multiverse-Core] [AllPay] - Version 13.0 - hooked into Essentials Economy for Multiverse-Core v2.5-b691
[02:02:01 INFO]: [Plot] Detected world load for 'plot'
[02:02:01 INFO]: [Plot]  - schematic: false
[02:02:01 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[02:02:01 INFO]: [Multiverse-Core] Version 2.5-b691 (API v18) Enabled - By Rigby, fernferret, lithium3141 and main--
[02:02:01 INFO]: [WorldGuard] Enabling WorldGuard v6.0.0-beta-05.1569-
[02:02:01 INFO]: [WorldGuard] Loading region data...
[02:02:01 INFO]: [VipSms] Enabling VipSms v1.08
[02:02:01 INFO]: [VipSms] developed by minecraft-elite.pl
[02:02:01 INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v2.1.5
[02:02:01 INFO]: [AsyncWorldEdit] Error loading strings file, using internal fallback.
[02:02:01 INFO]: [AsyncWorldEdit] BarAPI not found.
[02:02:01 INFO]: [AsyncWorldEdit] BlocksHub plugin not found.
[02:02:01 INFO]: [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix
[02:02:01 INFO]: [AsyncWorldEditInjector] New class factory set to: org.primesoft.asyncworldedit.injector.async.AsyncClassFactory
[02:02:01 WARN]: [AutoSaveWorld] Plugin AsyncWorldEdit attempted to establish connection https://api.github.com/repos/SBPrime/AsyncWorldEdit/releases in main server thread
[02:02:02 WARN]: [AutoSaveWorld] Plugin AsyncWorldEdit attempted to establish connection socket://api.github.com:443 in main server thread
[02:02:02 INFO]: [AsyncWorldEdit] You have the latest version of the plugin.
[02:02:02 INFO]: [AsyncWorldEdit] Enabled
[02:02:02 INFO]: [ArmorStandGUI] Enabling ArmorStandGUI v1.0.1
[02:02:02 WARN]: [AutoSaveWorld] Plugin ArmorStandGUI attempted to establish connection http://plugins.darkender.com/versions/?plugin=ArmorStandGUI in main server thread
[02:02:02 WARN]: [AutoSaveWorld] Plugin ArmorStandGUI attempted to establish connection socket://plugins.darkender.com:80 in main server thread
[02:02:02 WARN]: [AutoSaveWorld] Plugin ArmorStandGUI attempted to establish connection http://plugins.darkender.com/versions/message.php?plugin=ArmorStandGUI in main server thread
[02:02:03 WARN]: [AutoSaveWorld] Plugin ArmorStandGUI attempted to establish connection http://plugins.darkender.com/versions/permission.php?plugin=ArmorStandGUI in main server thread
[02:02:03 WARN]: [AutoSaveWorld] Plugin ArmorStandGUI attempted to establish connection http://plugins.darkender.com/versions/checkin.php in main server thread
[02:02:03 INFO]: [EssentialsChat] Enabling EssentialsChat vTeamCity
[02:02:03 INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.1
[02:02:03 INFO]: [PermissionsEx] Initializing sql backend
[02:02:03 WARN]: [AutoSaveWorld] Plugin PermissionsEx attempted to establish connection socket://localhost:3306 in main server thread
[02:02:03 WARN]: [AutoSaveWorld] Plugin PermissionsEx attempted to establish connection socket://localhost:3306 in main server thread
[02:02:03 INFO]: [PermissionsEx] Successfully connected to SQL database
[02:02:03 INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[02:02:03 INFO]: [Vault][Permission] PermissionsEx hooked.
[02:02:03 INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[02:02:03 INFO]: Essentials: Using PermissionsEx based permissions.
[02:02:03 INFO]: [RandomTeleport] Enabling RandomTeleport vmaven-version-number
[02:02:03 INFO]: [RandomTP] Auto-Updater disabled! If you would like to have RandomTP Update itself please set Enable to true!
[02:02:03 INFO]: [RandomTP] Enabled!
[02:02:03 INFO]: [MineResetLite] Enabling MineResetLite v0.3.6
[02:02:03 INFO]: [MineResetLite] MineResetLite version 0.3.6 enabled!
[02:02:03 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[02:02:03 INFO]: [ChestMaster] Enabling ChestMaster v1.5
[02:02:03 INFO]: [CHM] Enabling ChestMaster, Version: 1.5
[02:02:04 INFO]: [HubBasics] Enabling HubBasics v3.0.5
[02:02:04 ERROR]: Error occurred while enabling HubBasics v3.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at me.Fabricio20.Main.registerCommands(Main.java:143) ~[?:?]
        at me.Fabricio20.Main.initPlugin(Main.java:119) ~[?:?]
        at me.Fabricio20.Main.onEnable(Main.java:95) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:742) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:629) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:627) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:530) [craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_31]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_31]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-da32fe1-37102a0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
        ... 19 more

Well, the plugin seems to work with some features... In some of them it just derps and doesn't know what to do. :v

**Comment by Fabricio20** [comment]
I mean, join your server and do /bukkit:version
And send me what it returns to you, that's a problem related to the server JAR. Only some versions are supported. I've tested it with 1.8 and 1.7/1.8 ( Protocol Hack ), they have the class "IChatBaseComponent" from BungeeCord inside them.

**Comment by SidiXis** [comment]
CraftBukkit version git-Spigot-da32fe1-37102a0 (MC:1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Kinda outdated version, I guess.... :I

**Comment by Fabricio20** [comment]
Yes, You are behind by 305 versions, I've tested with git-Spigot-952179b-7bdb8f9 ( 53 Versions  Behind ), if you want, I can send you the jar file of this version, it just have some bug fixes and no changes to nms ( Wich means no plugins will be broken )

**Comment by SidiXis** [comment]
I've already updated my jar, works flawless, thanks a lot! ;)

**Comment by Fabricio20** [comment]
:P
