### ISSUE TITLE
I Dont Even Know Where To Begin With The Errors!

### ISSUE THREAD

**Issue by john1234brown** [Fabricio20/HubBasics#14]
Alright So i setup the quick warp with the compass and when you use the compass it opens up the quickwarp gui and i have my quick warps which i added in but when you click on one of them it allows you to move it none of the commands get executed and also i set in the configs to not allow moving of items in inventory and i wasnt even op when i tryed this and i could move items freelly in my inventory and in the quickwarp gui and when you click on the item in quickwarp gui a gaint error appears in console here it is 
```
[19:32:53 ERROR]: Could not pass event InventoryClickEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Bukkit-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [server.jar:git-Bukkit-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at me.Fabricio20.Bukkit.Listeners.Item.ItemMoveListener.onItemMove(ItemMoveListener.java:19) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[server.jar:git-Bukkit-7019900]
	... 14 more
[19:32:53 ERROR]: Could not pass event InventoryClickEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Bukkit-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [server.jar:git-Bukkit-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at me.Fabricio20.Bukkit.Listeners.Item.ItemClickChest.onClick(ItemClickChest.java:35) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[server.jar:git-Bukkit-7019900]
	... 14 more
[19:32:53 ERROR]: Could not pass event InventoryClickEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Bukkit-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [server.jar:git-Bukkit-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at me.Fabricio20.Bukkit.Listeners.Chest.SettingsChestClick.onClick(SettingsChestClick.java:21) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[server.jar:git-Bukkit-7019900]
	... 14 more
[19:32:55 ERROR]: Could not pass event InventoryClickEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Bukkit-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [server.jar:git-Bukkit-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at me.Fabricio20.Bukkit.Listeners.Item.ItemMoveListener.onItemMove(ItemMoveListener.java:19) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[server.jar:git-Bukkit-7019900]
	... 14 more
[19:32:55 ERROR]: Could not pass event InventoryClickEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Bukkit-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [server.jar:git-Bukkit-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at me.Fabricio20.Bukkit.Listeners.Item.ItemClickChest.onClick(ItemClickChest.java:35) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[server.jar:git-Bukkit-7019900]
	... 14 more
[19:32:55 ERROR]: Could not pass event InventoryClickEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Bukkit-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [server.jar:git-Bukkit-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [server.jar:git-Bukkit-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at me.Fabricio20.Bukkit.Listeners.Chest.SettingsChestClick.onClick(SettingsChestClick.java:21) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[server.jar:git-Bukkit-7019900]
	... 14 more
```
do you know what might help fix this i know that it means that the Inventory click Event Listener isnt working or missing so any suggestions on how to fix this

**Comment by john1234brown** [comment]
im going to download your source code and see if i can fix it i dont know that much about listeners and events so dont hold your breath xD well im going to see if i can get it will im waiting for your reply lets see first time working on a big plugin i have only made something that uses multiverse to so when you do /spawn it just makes you do /mv spawn instead so yeah pretty easy to make that one ill see what i can do

**Comment by john1234brown** [comment]
Um what encoding did you use on the following files RightClickListener.java, ItemClickChest.java, ItemMoveListener.java 

becuase i see this special symbol � and i cant save the file without swapping the encoding of it to UTF-8 and when i do it messes up the color code so yeah i dont know what to do about that

**Comment by john1234brown** [comment]
i think i might know what to do maybe updating some of the files to like Craftbukkit 1.8.3 since im running on spigot 1.8.3 or i think i am i dont know

**Comment by john1234brown** [comment]
i gave up on trying to fix your plugin it started working and whatever i tried doing after i got it working to a point then stopped so i just gave up

**Comment by Fabricio20** [comment]
That's related to an update, you are the first reporting this, so I'll need to check.

**Comment by john1234brown** [comment]
oh well i almost got it working on my own but again i had to keep saving it in utf-8 becuase of what you had it set to with that little wierd symbol which made it not have color codes you know the replace(& , ? );
line or something like that

**Comment by john1234brown** [comment]
here go and download this i did this to the files and got it working but i cant get the color codes working agian here is my dropbox link once you download it tell me and ill remove it off of dropbox k 
https://www.dropbox.com/s/txzu0mnosk1ttua/Bukkit%201.8%202%20Test.zip?dl=0

**Comment by john1234brown** [comment]
all i did was modify the bukkit 1.8.1 rv thing parts plus some of the other parts

**Comment by john1234brown** [comment]
I DID IT I FIXED YOUR PLUGIN IM SO HAPPY i got it working for spigot 1.8.1 ill see if it will work for 1.8.3 uploading it to my friends server
do you want the source files or stuff huh

**Comment by john1234brown** [comment]
if so here is the dropbox link to it
here is the link to its source code 
https://www.dropbox.com/s/txzu0mnosk1ttua/Bukkit%201.8%202%20Test.zip?dl=0

**Comment by john1234brown** [comment]
well you know what my freinds server is in spigot 1.8.3 and he cant change it so im going to try to add the spigot 1.8.3 files im hoping i can do this because i really enjoy the feeling of success when coding xD

**Comment by Fabricio20** [comment]
Well, good luck! If you need any help/explanation on my source code feel free to ask here :)

**Comment by john1234brown** [comment]
just so you know i gave up on trying to fix this my self so i hope you got it fixed becuase i really want to use this plugin for my freinds server
