### ISSUE TITLE
hubbasic does not work bungee 1.16

### ISSUE THREAD

**Issue by koeienboy22** [Fabricio20/HubBasics#143]
I updated the bungeecord to support for 1.16 when updating the hubbasic on the bungee no longer works so players can no longer do /lobby & /hub

bungee consoler log:

01:38:39 [WARNING] Exception encountered when loading plugin: HubBasics
java.lang.ExceptionInInitializerError
at net.notfab.hubbasics.bungee.HubBasics.onEnable(HubBasics.java:30)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NullPointerException
at java.util.EnumMap.<init>(EnumMap.java:139)
at net.notfab.hubbasics.bungee.managers.HBLogger.<clinit>(HBLogger.java:29)
... 5 more

bungeecord is 1.16
hubbasic-bungeecord is 6.11.4

**Comment by Snowy001** [comment]
having this same issue on 1.15.2

**Comment by Fabricio20** [comment]
This has been fixed as of commit https://github.com/Fabricio20/HubBasics/commit/8867a9e31711a41d38a2a5941ada4974cf46e96d
