### ISSUE TITLE
New Error Since Update

### ISSUE THREAD

**Issue by RemcoMusic** [Fabricio20/HubBasics#16]
Hey man first of all a great working full plugin! But I ran into a problem with the last update

Fault:
[11:32:13] [Server thread/INFO]: JochemWok[/127.0.0.1:49569] logged in with entity id 372 at ([world]-2005.232616495433, 71.5, -4444.783116456261)
[11:32:13] [Server thread/INFO]: Sync started...
[11:32:13] [Server thread/INFO]: Unknown Server
[11:32:13] [Server thread/INFO]: Sync start bottom...
[11:32:20] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to HubBasics v3.0.5
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:190) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1173) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:18) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
at me.Fabricio20.Bukkit.Constructors.HubChest.getDisplayName(HubChest.java:101) ~[?:?]
at me.Fabricio20.Bukkit.Constructors.HubChest.<init>(HubChest.java:40) ~[?:?]
at me.Fabricio20.Bukkit.Listeners.HubChest.CHEST_LeftClickListener.onLeftClick(CHEST_LeftClickListener.java:22) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
... 18 more
[11:33:30] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[11:33:30] [Server thread/INFO]: [0;37;1mPermissions reloaded[m

**Comment by Fabricio20** [comment]
If you have any configs on the Chests directory under HubBasics plugin folder, please paste them here, I need to check it.

**Comment by RemcoMusic** [comment]
I only have one config under the directory Chests. And that is QuickWarps

Config QuickWarps:

# +----------------------------------------------------+
# <                HubBasics Chest File                >
# <  Change with caution / Color codes are supported!  >
# +----------------------------------------------------+

# The Chest Hows / Maximum is 6
Rows: 3
PerWorld: false
Items:
  Spetsnaz:
    Material: IRON_PICKAXE
    Name: '&cSpetsnaz'
    Lore:
    - '&aTeleporteer naar &cSpetsnaz'
    Command: /warp Sspetsnaz
    Console: false
    Permission: ExampleItem.use
    UsePerm: false
    Slot: 1
    ViewPermEnabled: false
    ViewPerm: ExampleItem.see
  Duitsland:
    Material: TNT
    Name: '&eDuitsland'
    Lore:
    - '&aTeleporteer naar &eDuitsland'
    Command: /warp Sduitsland
    Console: false
    Permission: ExampleItem.use
    UsePerm: false
    Slot: 7
    ViewPermEnabled: false
    ViewPerm: ExampleItem.see
  Nederland:
    Material: WATER_BUCKET
    Name: '&6Nederland'
    Lore:
    - '&aTeleporteer naar &6Nederland'
    Command: /warp Snederland
    Console: false
    Permission: ExampleItem.use
    UsePerm: false
    Slot: 3
    ViewPermEnabled: false
    ViewPerm: ExampleItem.see
  Canada:
    Material: SAPLING
    Name: '&fCanada'
    Lore:
    - '&aTeleporteer naar &fCanada'
    Command: /warp Scanada
    Console: false
    Permission: ExampleItem.use
    UsePerm: false
    Slot: 5
    ViewPermEnabled: false
    ViewPerm: ExampleItem.see
  Terug:
    Material: ARROW
    Name: '&7Hub'
    Lore:
    - '&aTeleporteer naar &7Hub'
    Command: /hub
    Console: false
    Permission: ExampleItem.use
    UsePerm: false
    Slot: 22
    ViewPermEnabled: false
    ViewPerm: ExampleItem.see

**Comment by Fabricio20** [comment]
Ok, did you make this config or just edited what was there?

**Comment by RemcoMusic** [comment]
I just Edited it

**Comment by Fabricio20** [comment]
Ok, seems like it's a problem with the old chest system, going to make a fix right now..

**Comment by RemcoMusic** [comment]
And addes some things by copiën the old ones

**Comment by RemcoMusic** [comment]
Thanks man!!!
