### ISSUE TITLE
NPE on PlayerJoinEvent

### ISSUE THREAD

**Issue by stonegray** [Fabricio20/HubBasics#163]
Version info:
- HubBasics `v6.11.4`
- Tuinity `1.16.4`

This prints many hundreds of times into the console after the first player joins the server.

```
[12:53:18 ERROR]: Could not pass event PlayerInteractEvent to HubBasics v6.11.4
java.lang.NullPointerException: null
        at net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:510) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1552) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1191) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1184) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1160) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[12:53:19 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.Unknown.inventory.CraftItemStack
[12:53:19 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:116)
[12:53:19 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
[12:53:19 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[12:53:19 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[12:53:19 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[12:53:19 WARN]:        at java.base/java.lang.Class.forName(Class.java:315)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.getCraftItemstack(NBTReflectionUtils.java:14)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.getNMSItemStack(NBTReflectionUtils.java:46)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:213)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
[12:53:19 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source)
[12:53:19 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:53:19 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:53:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:53:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[12:53:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:510)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1552)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1191)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1184)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1160)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[12:53:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[12:53:19 WARN]: java.lang.NullPointerException
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.getNMSItemStack(NBTReflectionUtils.java:48)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:213)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
[12:53:19 WARN]:        at net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
[12:53:19 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source)
[12:53:19 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:53:19 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:53:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:53:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[12:53:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:510)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1552)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1191)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1184)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1160)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
[12:53:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[12:53:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[12:53:19 ERROR]: Could not pass event PlayerInteractEvent to HubBasics v6.11.4
java.lang.NullPointerException: null
        at net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:510) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1552) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1191) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1184) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1160) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        ```

**Comment by stonegray** [comment]
Resolved after update to https://github.com/Fabricio20/HubBasics/commit/f004d5a4ac791b4bdd5b8cab196933940ac50c33 (6.11.9)
