### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RemcoMusic** [Fabricio20/HubBasics#17]

**Comment by RemcoMusic** [comment]
Do I have to delete the old config from the folder Chests?

**Comment by Fabricio20** [comment]
Yes, it's outdated. Check the new config here: https://github.com/Fabricio20/HubBasics/blob/master/Chest-System-Explain.yml

**Comment by RemcoMusic** [comment]
Yea I'll will let you know if everything is working, testing right now everything

**Comment by RemcoMusic** [comment]
Now I get this one:

[16:26:36] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1127) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1051) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:241) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at me.Fabricio20.Bukkit.Listeners.Player.RightClickListener.Interact(RightClickListener.java:137) [HubBasics.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:190) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:694) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Chests must have a size that is a multiple of 9!
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createInventory(CraftServer.java:1529) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.Bukkit.createInventory(Bukkit.java:934) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at me.Fabricio20.Bukkit.Constructors.HubChest.<init>(HubChest.java:40) ~[?:?]
	at me.Fabricio20.Bukkit.Listeners.HubChest.CHEST_Command.onCommand(CHEST_Command.java:20) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	... 30 more

And it did the config in the folder like this Chests:

http://prntscr.com/7bhnh5
