### ISSUE TITLE
When 1.17 update will arrive ?

### ISSUE THREAD

**Issue by MrGrOGC** [Fabricio20/HubBasics#176]
**Hello**, i do this post because since some time I search the answer to this question and i found nothing on internet :/

So could you tell me **when the 1.17 update will arrive** ? It's important for my 1.17 servers because the 1.16 do lot of errors on my consoles even if nothing happens on servers.

**Sorry again** for this post and thank you for your futur answers !
Regards,
MrGrOGC.

**Comment by Fabricio20** [comment]
Hello, can you post the errors you are encountering in 1.17? The plugin from 1.16 should be working just fine in 1.17.

**Comment by MrGrOGC** [comment]
Yes, my errors :
`<html>
<body>


[17:49:42] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to HubBasics v6.11.9
--
1083 | java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(String)" is null
1084 | at net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onItemMove(ItemListener.java:25) ~[HubBasics-Spigot.jar:?]
1085 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
1086 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-356]
1087 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-356]
1088 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-356]
1089 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-356]
1090 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:2970) ~[app:?]
1091 | at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:18) ~[app:?]
1092 | at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:7) ~[app:?]
1093 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
1094 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-356]
1095 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
1096 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
1097 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[patched_1.17.1.jar:git-Paper-356]
1098 | at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-356]
1099 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
1100 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1401) ~[patched_1.17.1.jar:git-Paper-356]
1101 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1394) ~[patched_1.17.1.jar:git-Paper-356]
1102 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
1103 | at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1372) ~[patched_1.17.1.jar:git-Paper-356]
1104 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Paper-356]
1105 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-356]
1106 | at java.lang.Thread.run(Thread.java:831) ~[?:?]


</body>
</html>`

Plugin is in last version

**Comment by MrGrOGC** [comment]
```
[17:51:46] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
--
1110 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
1111 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
1112 | [17:51:46] [Server thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
1113 | [17:51:46] [Server thread/WARN]: at java.base/java.lang.Class.forName0(Native Method)
1114 | [17:51:46] [Server thread/WARN]: at java.base/java.lang.Class.forName(Class.java:375)
1115 | [17:51:46] [Server thread/WARN]: at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.getNewNBTTag(NBTReflectionUtils.java:24)
1116 | [17:51:46] [Server thread/WARN]: at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:216)
1117 | [17:51:46] [Server thread/WARN]: at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
1118 | [17:51:46] [Server thread/WARN]: at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
1119 | [17:51:46] [Server thread/WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
1120 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
1121 | [17:51:46] [Server thread/WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
1122 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
1123 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
1124 | [17:51:46] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
1125 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
1126 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1815)
1127 | [17:51:46] [Server thread/WARN]: at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
1128 | [17:51:46] [Server thread/WARN]: at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
1129 | [17:51:46] [Server thread/WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
1130 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
1131 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
1132 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
1133 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1423)
1134 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
1135 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
1136 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1401)
1137 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1394)
1138 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
1139 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1372)
1140 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283)
1141 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
1142 | [17:51:46] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
1143 | [17:51:46] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "nbttag" is null
1144 | [17:51:46] [Server thread/WARN]: at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:219)
1145 | [17:51:46] [Server thread/WARN]: at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
1146 | [17:51:46] [Server thread/WARN]: at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
1147 | [17:51:46] [Server thread/WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
1148 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
1149 | [17:51:46] [Server thread/WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
1150 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
1151 | [17:51:46] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
1152 | [17:51:46] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
1153 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
1154 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1815)
1155 | [17:51:46] [Server thread/WARN]: at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
1156 | [17:51:46] [Server thread/WARN]: at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
1157 | [17:51:46] [Server thread/WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
1158 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
1159 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
1160 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
1161 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1423)
1162 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
1163 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
1164 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1401)
1165 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1394)
1166 | [17:51:46] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
1167 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1372)
1168 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283)
1169 | [17:51:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
1170 | [17:51:46] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
```

And this is another errors :/

**Comment by Fabricio20** [comment]
Hey there, I'll try looking into this issue during this weekend, based on the stacktraces looks like some things HubBasics depends on either got removed or completely changed so it _might_ not be an easy fix.

**Comment by Fabricio20** [comment]
Hello, as of yesterday's update I believe 1.17 should be working just fine, let me know if it works for you.

**Comment by MrGrOGC** [comment]
Wow man, it's really nice job ! My server work good now, when i place or break block nothing appears on console so I think it's good for me ! 😃 
Just menu-opener don't give at spawn but i think it's my config.

Thanks a lot for everything you have done Fabricio. 👏
