### ISSUE TITLE
ERROR when i place or destroy block

### ISSUE THREAD

**Issue by Krzychu4u** [Fabricio20/HubBasics#177]
> [20:26:21 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
[20:26:21 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[20:26:21 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[20:26:21 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[20:26:21 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[20:26:21 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[20:26:21 WARN]:        at HubBasics-Spigot[1.7-1.16].jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.getNewNBTTag(NBTReflectionUtils.java:24)
[20:26:21 WARN]:        at HubBasics-Spigot[1.7-1.16].jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:216)
[20:26:21 WARN]:        at HubBasics-Spigot[1.7-1.16].jar//net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
[20:26:21 WARN]:        at HubBasics-Spigot[1.7-1.16].jar//net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
[20:26:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source)
[20:26:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:26:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:26:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:26:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[20:26:21 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[20:26:21 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
[20:26:21 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1815)
[20:26:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[20:26:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[20:26:21 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[20:26:21 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[20:26:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[20:26:21 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "nbttag" is null
[20:26:21 WARN]:        at HubBasics-Spigot[1.7-1.16].jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:219)
[20:26:21 WARN]:        at HubBasics-Spigot[1.7-1.16].jar//net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
[20:26:21 WARN]:        at HubBasics-Spigot[1.7-1.16].jar//net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
[20:26:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source)
[20:26:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:26:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:26:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:26:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[20:26:21 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[20:26:21 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
[20:26:21 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1815)
[20:26:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[20:26:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[20:26:21 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[20:26:21 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[20:26:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[20:26:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[20:26:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[20:26:21 ERROR]: Could not pass event PlayerInteractEvent to HubBasics v6.11.9
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(String)" is null
        at net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103) ~[HubBasics-Spigot[1.7-1.16].jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-388]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1815) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

and this when plugin loading 
`[20:25:53 WARN]: [HubBasics] [JumpPads] Invalid Particle Effect [CLOUD] for Jump Pad`
CLOUD is default settings 

about server:
Paper 1.17.1-(#388) on FlameCord 0.6.4

**Comment by Fabricio20** [comment]
Hey, thanks for reporting, this is related to 1.17 and I'm going to track the issue on #176, I'll try looking into it this weekend.
