### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by RemcoMusic** [Fabricio20/HubBasics#18]
[17:02:28] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:736) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at me.Fabricio20.Bukkit.Constructors.HubChest.<init>(HubChest.java:59) ~[?:?]
	at me.Fabricio20.Bukkit.Listeners.HubChest.CHEST_RightClickListener.onRightClick(CHEST_RightClickListener.java:22) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.8.6.jar:git-Spigot-ae40327-21681b3]
	... 17 more

**Comment by Fabricio20** [comment]
Can you screenshot your server.yml please?

**Comment by RemcoMusic** [comment]
I didn't changed it till last time 

http://prntscr.com/7bia6u

**Comment by Fabricio20** [comment]
Is the chest even opening?

**Comment by RemcoMusic** [comment]
No it isn't in my inventory and the problem is this error is when players do any thing in a other world
