### ISSUE TITLE
plguin does not work on 1.18.1

### ISSUE THREAD

**Issue by koeienboy22** [Fabricio20/HubBasics#180]
when updating the server to 1.18.1 (due to security flaws of MC) the lobby plugin doesn't work on 1.18.1 it sees the plugin works just as it seems only the compass part doesn't work anymore it also says that the server an unsupported version has the server version is 1.18.1 paperMC

> [20:18:03] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[20:18:03] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[20:18:03] [Server thread/WARN]: 	at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.getNBTTagCompound(NBTReflectionUtils.java:84)
[20:18:03] [Server thread/WARN]: 	at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:225)
[20:18:03] [Server thread/WARN]: 	at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
[20:18:03] [Server thread/WARN]: 	at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
[20:18:03] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:18:03] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1873)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[20:18:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:18:03] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.nbt.NBTTagCompound.hasKey(java.lang.String)
[20:18:03] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[20:18:03] [Server thread/WARN]: 	at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTReflectionUtils.hasKey(NBTReflectionUtils.java:229)
[20:18:03] [Server thread/WARN]: 	at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(NBTItem.java:50)
[20:18:03] [Server thread/WARN]: 	at HubBasics-Spigot.jar//net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103)
[20:18:03] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:18:03] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501)
[20:18:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1873)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[20:18:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[20:18:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:18:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to HubBasics v6.11.10
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.notfab.hubbasics.spigot.nms.nbt.NBTItem.hasKey(String)" is null
	at net.notfab.hubbasics.spigot.listeners.v1_9.ItemListener.onRightClick(ItemListener.java:103) ~[HubBasics-Spigot.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[paper-1.18.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[paper-1.18.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[paper-1.18.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1873) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-82]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Fabricio20** [comment]
Hello, this is related to #178, I've given an update there and a fixed version should be available soon.
