### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by RikoDEV** [Fabricio20/HubBasics#42]
Hi @Fabricio20,
J have error in the console:
[14:23:07 WARN]: java.lang.reflect.InvocationTargetException
[14:23:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:23:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:23:07 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:23:07 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[14:23:07 WARN]:        at net.notfab.HubBasics.Bukkit.NMS.Title.send(Title.java:235)
[14:23:07 WARN]:        at net.notfab.HubBasics.Bukkit.Listeners.ConnectionListener.onJoin(ConnectionListener.java:45)
[14:23:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:23:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:23:07 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:23:07 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[14:23:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[14:23:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:23:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[14:23:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[14:23:07 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:23:07 WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3
[14:23:07 WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:56)
[14:23:07 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.ChatDeserializer.a(SourceFile:501)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.ChatDeserializer.a(SourceFile:512)
[14:23:07 WARN]:        at net.minecraft.server.v1_9_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:205)
[14:23:07 WARN]:        ... 25 more
[14:23:07 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3
[14:23:07 WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
[14:23:07 WARN]:        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
[14:23:07 WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:497)
[14:23:07 WARN]:        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
[14:23:07 WARN]:        at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
[14:23:07 WARN]:        at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
[14:23:07 WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:44)
[14:23:07 WARN]:        ... 29 more

**Comment by Fabricio20** [comment]
When does that happen?
