### ISSUE TITLE
Error during server startup

### ISSUE THREAD

**Issue by RikoDEV** [Fabricio20/HubBasics#47]
Hi, I have a problem with the latest version of your plugin. When you start the server displays a mixup with the command Holograms. Engine server is PaperSpigot 1.10.2.
**I would add that the config is not generated (is empty)**

**Console log:**
```
[08:11:35] [Server thread/INFO]: Starting minecraft server version 1.10.2
[08:11:35] [Server thread/INFO]: Loading properties
[08:11:35] [Server thread/INFO]: Default game type: SURVIVAL
[08:11:35] [Server thread/INFO]: This server is running Paper version git-Paper-809 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[08:11:35] [Server thread/INFO]: Server Ping Player Sample Count: 12
[08:11:35] [Server thread/INFO]: Using 4 threads for Netty based IO
[08:11:35] [Server thread/INFO]: Debug logging is disabled
[08:11:36] [Server thread/INFO]: Spigot Timings: true - Verbose: true - Interval: 5m - Length: 60m
[08:11:36] [Server thread/INFO]: Generating keypair
[08:11:36] [Server thread/INFO]: Starting Minecraft server on *:25554
[08:11:37] [Server thread/INFO]: Using epoll channel type
[08:11:37] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[08:11:37] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[08:11:37] [Server thread/WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
[08:11:37] [Server thread/INFO]: [AuthMe] Loading AuthMe v${bukkitplugin.versionCode}
[08:11:37] [Server thread/INFO]: [HubBasics] Loading HubBasics v5.0
[08:11:37] [Server thread/INFO]: [TitleManager] Loading TitleManager v1.5.12
[08:11:37] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.4-SNAPSHOT;3583-28d4587
[08:11:37] [Server thread/INFO]: [AuthMeBridge] Loading AuthMeBridge v1.6
[08:11:37] [Server thread/INFO]: [CustomJoinItems] Loading CustomJoinItems v1.5.2
[08:11:37] [Server thread/INFO]: [ChestCommands] Loading ChestCommands v3.1.4
[08:11:37] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.1.3-SNAPSHOT;1679-f006a95
[08:11:37] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[08:11:37] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[08:11:37] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[08:11:37] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[08:11:37] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[08:11:37] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[08:11:37] [Server thread/INFO]: Preparing level "world"
[08:11:37] [Server thread/INFO]: -------- World Settings For [world] --------
[08:11:37] [Server thread/INFO]: Mob Spawn Range: 4
[08:11:37] [Server thread/INFO]: Cactus Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: Cane Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: Melon Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: Sapling Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: Wheat Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[08:11:37] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[08:11:37] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[08:11:37] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[08:11:37] [Server thread/INFO]: Random Lighting Updates: false
[08:11:37] [Server thread/INFO]: Structure Info Saving: true
[08:11:37] [Server thread/INFO]: Max Entity Collisions: 8
[08:11:37] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[08:11:37] [Server thread/INFO]: Max TNT Explosions: 10
[08:11:37] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[08:11:37] [Server thread/INFO]: Item Despawn Rate: 6000
[08:11:37] [Server thread/INFO]: Item Merge Radius: 2.5
[08:11:37] [Server thread/INFO]: Arrow Despawn Rate: 1200
[08:11:37] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[08:11:37] [Server thread/INFO]: View Distance: 3
[08:11:37] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[08:11:37] [Server thread/INFO]: Experience Merge Radius: 3.0
[08:11:37] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[08:11:38] [Server thread/INFO]: Preparing start region for level 0 (Seed: 3046549573733784391)
[08:11:38] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[08:11:38] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[08:11:38] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[08:11:38] [Server thread/INFO]: [AuthMe] Enabling AuthMe v${bukkitplugin.versionCode}
[08:11:39] [Server thread/INFO]: [AuthMe] SQLite driver loaded
[08:11:39] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[08:11:39] [Server thread/INFO]: [AuthMe] Hooked into PermissionsEx!
[08:11:39] [Server thread/INFO]: [AuthMe] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[08:11:39] [Server thread/INFO]: [AuthMe] Development builds are available on our jenkins, thanks to f14stelt.
[08:11:39] [Server thread/INFO]: [AuthMe] Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[08:11:39] [Server thread/INFO]: [AuthMe] AuthMe ${bukkitplugin.versionCode} correctly enabled!
[08:11:39] [Server thread/INFO]: [AuthMe] Automatically purging the database...
[08:11:39] [Server thread/INFO]: [AuthMe] No players to purge
[08:11:39] [Server thread/INFO]: [HubBasics] Enabling HubBasics v5.0
[08:11:39] [Server thread/ERROR]: Error occurred while enabling HubBasics v5.0 (Is it up to date?)
java.lang.NullPointerException
	at net.notfab.hubbasics.commands.HologramsCmd.<init>(HologramsCmd.java:26) ~[?:?]
	at net.notfab.hubbasics.managers.CommandManager.<init>(CommandManager.java:34) ~[?:?]
	at net.notfab.hubbasics.HubBasics.onEnable(HubBasics.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.2.jar:git-Paper-809]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[08:11:39] [Server thread/INFO]: [HubBasics] Disabling HubBasics v5.0
[08:11:39] [Server thread/ERROR]: Error occurred while disabling HubBasics v5.0 (Is it up to date?)
java.lang.NullPointerException
	at net.notfab.hubbasics.HubBasics.onDisable(HubBasics.java:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347) [patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:323) [patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.2.jar:git-Paper-809]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by LorgeN** [comment]
Error fixed. This error appeared because of the order CommandManager was loaded relative to ModuleManager.
