### ISSUE TITLE
Cannot pass PlayerJoinEvent to Hub Basics

### ISSUE THREAD

**Issue by LeCodeCo** [Fabricio20/HubBasics#57]
Hi, the plugin is amazing, but this one thing is bothering me. Every time someone joins the console shows this: `[06:32:43 INFO]: UUID of player Notch is CENCORED
[06:32:43 ERROR]: Could not pass event PlayerJoinEvent to HubBasics v5.0-DEVELOPMENT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:333) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:159) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:832) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-9797151-301db84]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.teleport(CraftPlayer.java:475) ~[spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftEntity.teleport(CraftEntity.java:226) ~[spigot.jar:git-Spigot-9797151-301db84]
        at net.notfab.hubbasics.modules.JoinTeleport.onPlayerConnect(JoinTeleport.java:49) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-9797151-301db84]
        ... 14 more`

Its really annoying for me since it makes checking the console difficult. Please can you fix it? Or suggest what I'm doing wrong?

**Comment by FreeKillGR** [comment]
i need help with this as well 

its a worldguard problem btw
