### ISSUE TITLE
Iron Bars

### ISSUE THREAD

**Issue by fiba1** [Fabricio20/HubBasics#64]
'22':
        Type: IRON_BARS
        Amount: 1
        Name: §8Test
        Lore:
        - Example
        Droppable: true
        Commands:
          OnInventoryClick:
            Command: commandhere
            UseConsole: false

How do I specify iron bars? everything I try I get an error.

> Error occurred while enabling HubBasics v5.0-DEVELOPMENT (Is it up to date?)
java.lang.IllegalArgumentException: Given item type isn't viable!
        at net.notfab.hubbasics.utils.ItemUtils.deserialize(ItemUtils.java:143) ~[?:?]
        at net.notfab.hubbasics.objects.Menu.<init>(Menu.java:88) ~[?:?]
        at net.notfab.hubbasics.modules.GraphicalMenus.lambda$onEnable$0(GraphicalMenus.java:47) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_111]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_111]
        at net.notfab.hubbasics.modules.GraphicalMenus.onEnable(GraphicalMenus.java:47) ~[?:?]
        at net.notfab.hubbasics.abstracts.module.Module.onEnableInternal(Module.java:48) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_111]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_111]
        at net.notfab.hubbasics.managers.ModuleManager.onEnable(ModuleManager.java:80) ~[?:?]
        at net.notfab.hubbasics.HubBasics.onEnable(HubBasics.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.reload(CraftServer.java:745) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by fiba1** [comment]
I didn't realize I could use the item ID.
