### ISSUE TITLE
Got this error, not entirely sure why

### ISSUE THREAD

**Issue by NocturneCZ** [Fabricio20/HubBasics#80]
Error occurred while enabling HubBasics v5.01121 (Is it up to date?)
java.lang.IllegalArgumentException: Given item type isn't viable!
        at net.notfab.hubbasics.utils.ItemUtils.deserialize(ItemUtils.java:143) ~[?:?]
        at net.notfab.hubbasics.objects.Menu.<init>(Menu.java:88) ~[?:?]
        at net.notfab.hubbasics.modules.GraphicalMenus.lambda$onEnable$0(GraphicalMenus.java:47) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_151]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_151]
        at net.notfab.hubbasics.modules.GraphicalMenus.onEnable(GraphicalMenus.java:47) ~[?:?]
        at net.notfab.hubbasics.abstracts.module.Module.onEnableInternal(Module.java:48) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_151]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_151]
        at net.notfab.hubbasics.managers.ModuleManager.onEnable(ModuleManager.java:80) ~[?:?]
        at net.notfab.hubbasics.HubBasics.onEnable(HubBasics.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:752) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-bb614f8-e40c9ef]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by Fabricio20** [comment]
Given item type isn't viable on one of your menus.
