### ISSUE TITLE
Exception using Elytra and Firework rocket

### ISSUE THREAD

**Issue by Capri205** [Fabricio20/HubBasics#83]
Hi. I get a lot of these whilst flying around my lobby. Using a build of spigot I did this morning, so should be latest Nothing critical. Keep up the good work!

[11:14:19] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-69774b3-ec2095d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[11:14:25] [Server thread/INFO]: [HubBasics] Loading HubBasics v6.0-DEVELOPMENT

```
[11:15:12] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to HubBasics v6.0-DEVELOPMENT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:931) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: net.notfab.hubbasics.spigot.nms.particle.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library
        at net.notfab.hubbasics.spigot.nms.particle.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1422) ~[?:?]
        at net.notfab.hubbasics.spigot.nms.particle.ParticleEffect$ParticlePacket.<init>(ParticleEffect.java:1348) ~[?:?]
        at net.notfab.hubbasics.spigot.nms.particle.ParticleEffect.display(ParticleEffect.java:603) ~[?:?]
        at net.notfab.hubbasics.spigot.nms.particle.ParticleEffect.display(ParticleEffect.java:622) ~[?:?]
        at net.notfab.hubbasics.spigot.modules.JumpPads.onPlayerMove(JumpPads.java:151) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
        ... 15 more
```

**Comment by Fabricio20** [comment]
Hm, big issue but thanks for reporting, looking into it right now.
